package content

import (
	"database/sql"
	"errors"
)

const mediaSchemaSQLite = `CREATE TABLE media (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 section TEXT NOT NULL CHECK(section IN ('exercise','training')),
 kind TEXT NOT NULL CHECK(kind IN ('video','photo')),
 title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', category TEXT NOT NULL DEFAULT '',
 youtube_id TEXT NOT NULL DEFAULT '', photo_file TEXT NOT NULL DEFAULT '', video_file TEXT NOT NULL DEFAULT '',
 created_by TEXT NOT NULL, created_at TEXT NOT NULL,
 CHECK((kind='video' AND length(youtube_id)=11 AND photo_file='' AND video_file='') OR (kind='video' AND youtube_id='' AND photo_file='' AND video_file<>'') OR (kind='photo' AND youtube_id='' AND photo_file<>'' AND video_file='')),
 CHECK(section<>'exercise' OR kind='video')
)`
const mediaSchemaPostgres = `CREATE TABLE IF NOT EXISTS media (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 section TEXT NOT NULL CHECK(section IN ('exercise','training')),
 kind TEXT NOT NULL CHECK(kind IN ('video','photo')),
 title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', category TEXT NOT NULL DEFAULT '',
 youtube_id TEXT NOT NULL DEFAULT '', photo_file TEXT NOT NULL DEFAULT '', video_file TEXT NOT NULL DEFAULT '',
 created_by TEXT NOT NULL, created_at TEXT NOT NULL,
 CHECK((kind='video' AND length(youtube_id)=11 AND photo_file='' AND video_file='') OR (kind='video' AND youtube_id='' AND photo_file='' AND video_file<>'') OR (kind='photo' AND youtube_id='' AND photo_file<>'' AND video_file='')),
 CHECK(section<>'exercise' OR kind='video')
)`

func migrate(db *sql.DB, dialect string) error {
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if dialect == "postgres" {
		if _, err = tx.Exec(mediaSchemaPostgres); err != nil {
			return err
		}
		if _, err = tx.Exec(`CREATE TABLE IF NOT EXISTS content_state (id INTEGER PRIMARY KEY CHECK(id=1), revision BIGINT NOT NULL); INSERT INTO content_state(id,revision) VALUES(1,0) ON CONFLICT (id) DO NOTHING;`); err != nil {
			return err
		}
		if _, err = tx.Exec(`CREATE TABLE IF NOT EXISTS club_schema (id INTEGER PRIMARY KEY CHECK(id=1), version INTEGER NOT NULL); INSERT INTO club_schema VALUES(1,2) ON CONFLICT(id) DO NOTHING;`); err != nil {
			return err
		}
		var version int
		if err = tx.QueryRow("SELECT version FROM club_schema WHERE id=1 FOR UPDATE").Scan(&version); err != nil {
			return err
		}
		if version > 4 {
			return errors.New("database schema is newer than this application")
		}
		if version < 3 {
			if err = migratePages(tx, dialect); err != nil {
				return err
			}
		}
		if version < 4 {
			if err = migrateBingoCenter(tx); err != nil {
				return err
			}
			if _, err = tx.Exec("UPDATE club_schema SET version=4 WHERE id=1"); err != nil {
				return err
			}
		}
		return tx.Commit()
	}
	var version int
	if err = tx.QueryRow("PRAGMA user_version").Scan(&version); err != nil {
		return err
	}
	if version > 4 {
		return errors.New("database schema is newer than this application")
	}
	if version == 0 {
		if _, err = tx.Exec(mediaSchemaSQLite); err != nil {
			return err
		}
	} else if version == 1 {
		if _, err = tx.Exec("ALTER TABLE media RENAME TO media_v1"); err != nil {
			return err
		}
		if _, err = tx.Exec(mediaSchemaSQLite); err != nil {
			return err
		}
		if _, err = tx.Exec(`INSERT INTO media(id,section,kind,title,description,category,youtube_id,photo_file,created_by,created_at) SELECT id,section,kind,title,description,category,youtube_id,photo_file,created_by,created_at FROM media_v1; DROP TABLE media_v1;`); err != nil {
			return err
		}
	}
	if _, err = tx.Exec(`CREATE TABLE IF NOT EXISTS content_state (id INTEGER PRIMARY KEY CHECK(id=1), revision INTEGER NOT NULL); INSERT OR IGNORE INTO content_state VALUES(1,0); `); err != nil {
		return err
	}
	if version < 3 {
		if err = migratePages(tx, dialect); err != nil {
			return err
		}
	}
	if version < 4 {
		if err = migrateBingoCenter(tx); err != nil {
			return err
		}
	}
	if _, err = tx.Exec("PRAGMA user_version=4"); err != nil {
		return err
	}
	return tx.Commit()
}

var initialBingo = []string{
	"Te druk", "Slecht geslapen", "File", "Rugpijn", "Knie doet raar",
	"Gisteren al getraind", "Werkstress", "Familiedingetje", "Niet 100%", "Te laat overleg",
	"Volgende week zeker", "Telefoon leeg", "Mijn mace ligt nog in de auto", "Vakantie in de planning", "Weer is slecht",
	"Buikpijn", "Geen energie", "Sportbroek in de was", "Spierpijn", "Druk thuis",
	"Auto kapot", "Kind ziek", "Slecht weer verwacht", "Verjaardag", "Mijn mace heeft rustdag",
}

func migratePages(tx *sql.Tx, dialect string) error {
	for _, statement := range []string{
		"ALTER TABLE media ADD COLUMN sort_order BIGINT NOT NULL DEFAULT 0",
		"ALTER TABLE media ADD COLUMN deleted_at TEXT NOT NULL DEFAULT ''",
		"UPDATE media SET sort_order=-id",
		"CREATE TABLE bingo_cells (id INTEGER PRIMARY KEY CHECK(id BETWEEN 1 AND 25), text TEXT NOT NULL, checked INTEGER NOT NULL DEFAULT 0 CHECK(checked IN (0,1)), version INTEGER NOT NULL DEFAULT 1)",
	} {
		if _, err := tx.Exec(statement); err != nil {
			return err
		}
	}
	query := "INSERT INTO bingo_cells(id,text,checked) VALUES(?,?,?)"
	if dialect == "postgres" {
		query = "INSERT INTO bingo_cells(id,text,checked) VALUES($1,$2,$3)"
	}
	for index, text := range initialBingo {
		if _, err := tx.Exec(query, index+1, text, 0); err != nil {
			return err
		}
	}
	return nil
}

// Replace only the old free-square label; keep any member-written excuse.
func migrateBingoCenter(tx *sql.Tx) error {
	result, err := tx.Exec("UPDATE bingo_cells SET text='Mijn mace ligt nog in de auto', checked=0, version=version+1 WHERE id=13 AND text='Vrij vak'")
	if err != nil {
		return err
	}
	changed, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if changed > 0 {
		_, err = tx.Exec("UPDATE content_state SET revision=revision+1 WHERE id=1")
	}
	return err
}
