apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maceclubheemskerk
resources:
- app.yaml
- postgres-ca.yaml
- sessions-pvc.yaml
- videos-pvc.yaml
- route-vdzonsoftware.yaml
- secrets
images:
- digest: sha256:15e1189ee475d76b19544bbcff584d2e877230fa32b3fdd04e8b216c21da5948
  name: ghcr.io/robbertvdzon/maceclubheemskerk
  newName: ghcr.io/robbertvdzon/maceclubheemskerk
