apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maceclubheemskerk
resources:
- app.yaml
- postgres-ca.yaml
- sessions-pvc.yaml
- videos-pvc.yaml
- route-vdzonsoftware.yaml
- secrets
images:
- digest: sha256:c0bb39cc67f3f59e7949fdf7aded6ee3bc7705dc77facc1d049a385426c7b0a1
  name: ghcr.io/robbertvdzon/maceclubheemskerk
  newName: ghcr.io/robbertvdzon/maceclubheemskerk
