apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maceclubheemskerk
resources:
- app.yaml
- postgres-ca.yaml
- sessions-pvc.yaml
- videos-pvc.yaml
- route-vdzonsoftware.yaml
- secrets
images:
- digest: sha256:d5eb2f4937530acf5d81c260c25ed4aead33352cd52a9942598cc62cce504c64
  name: ghcr.io/robbertvdzon/maceclubheemskerk
  newName: ghcr.io/robbertvdzon/maceclubheemskerk
