apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maceclubheemskerk-sessions
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
