apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maceclubheemskerk-videos
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    volumeType: local
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
